# Mad-IPTV — projeye özel mpv ayarları (global mpv ayarına dokunmaz)
# Not: mpv'nin varsayılan kontrol çubuğu (OSC) açık. İsteyen uosc kurabilir
# (https://github.com/tomasklaen/uosc) ve burada osc=no yapabilir.
osc=yes
osd-bar=yes
border=yes
keep-open=no
save-position-on-quit=no
cache=yes
hwdec=auto-safe
sub-auto=fuzzy
volume=100
volume-max=130
# yumuşak altyazı görünümü
sub-font-size=46
sub-border-size=2.6
sub-shadow-offset=1.2
sub-color='#FFFFFFFF'
sub-border-color='#000000DD'
